vich_uploader:
    db_driver: orm

    mappings:
       sants_images:
            uri_prefix: /uploads/sants/
            upload_destination: '%kernel.project_dir%/public/uploads/sants'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
